services:
  db:
    container_name: postgres
    image: hub.mecan.ir/postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nw
    ports:
      - "5332:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    container_name: web
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - nw
    volumes:
      - static:/app/static/
      - media:/app/media/
    entrypoint: python manage.py runserver 0.0.0.0:8000

  nginx:
    container_name: nginx
    build: nginx/
    ports:
      - "9000:80"
    networks:
      - nw
    volumes:
      - static:/static/
      - media:/media/


volumes:
  db:
  media:
  static:

networks:
  nw: